version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    command: ["elasticsearch", "-E", "network.host=0.0.0.0",
              "-E", "discovery.zen.minimum_master_nodes=1"]
  #  volumes:
  #    - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
  logstash:
    build:
      context: logstash/
    command: ["logstash", "-f", "/etc/logstash/conf.d/"]
    ports:
      - "5000:5000"
      - "6666:6666"
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    ports:
      - "5601:5601"
    environment:
      - LOGSPOUT=ignore
      - SERVER_PORT=5601
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  logspout:
    image: gliderlabs/logspout:master
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "8100:8000"
    depends_on:
      - logstash
    command: syslog://logstash:6666
